Update helm chart and values.

diff --git a/helm/templates/deployment.yaml b/helm/templates/deployment.yaml
--- a/helm/templates/deployment.yaml
+++ b/helm/templates/deployment.yaml
@@ -14,33 +14,33 @@ spec:
       {{- include "ssoGateway.selectorLabels" . | nindent 6 }}
   template:
     metadata:
-      annotations:
-        # 1. Vault injector configuration
-        vault.hashicorp.com/agent-inject: 'true'
-        # set to 'true' if you are going to connect and query vault from your application
-        vault.hashicorp.com/agent-inject-token: 'false' 
-        # this makes sure the secret vault will only change during pod restart
-        vault.hashicorp.com/agent-pre-populate-only: 'true' 
-        # Must match cluster. Use one of: k8s-silver, k8s-gold, k8s-golddr, k8s-emerald
-        vault.hashicorp.com/auth-path: auth/k8s-{{ .Values.global.cluster }}  
-        vault.hashicorp.com/namespace: platform-services
-        # licenseplate-nonprod or licenseplate-prod are your options
-        vault.hashicorp.com/role: {{ .Values.global.vault.role }} 
-        # - The value is the path in Vault where the secret is located.
-        vault.hashicorp.com/agent-inject-secret-secrets: {{ .Values.global.licenseplate }}-{{ .Values.global.vault.engine }}/{{ .Values.kilnAPI.vault.secret }}
-        # - The template Vault Agent should use for rendering a secret:
-        vault.hashicorp.com/agent-inject-template-secrets: |
-          {{`{{- with secret `}}"{{ .Values.global.licenseplate }}-{{ .Values.global.vault.engine }}/{{ .Values.kilnAPI.vault.secret }}"{{` }}
-          {{- range $k, $v := .Data.data }}
-          {{ $k }}={{ $v }}{{ end -}}
-          {{- end `}} }}
-        # - The value is the path in Vault where the secret is located.
-        vault.hashicorp.com/agent-inject-secret-redis-password: {{ .Values.global.licenseplate }}-{{ .Values.global.vault.engine }}/{{ .Values.redis.vault.secret }}
-        # - The template Vault Agent should use for rendering a secret:
-        vault.hashicorp.com/agent-inject-template-redis-password: |
-          {{`{{- with secret `}}"{{ .Values.global.licenseplate }}-{{ .Values.global.vault.engine }}/{{ .Values.redis.vault.secret }}"{{` }}
-          {{ .Data.data.password }}
-          {{- end `}} }}
+      # annotations:
+      #   # 1. Vault injector configuration
+      #   vault.hashicorp.com/agent-inject: 'true'
+      #   # set to 'true' if you are going to connect and query vault from your application
+      #   vault.hashicorp.com/agent-inject-token: 'false' 
+      #   # this makes sure the secret vault will only change during pod restart
+      #   vault.hashicorp.com/agent-pre-populate-only: 'true' 
+      #   # Must match cluster. Use one of: k8s-silver, k8s-gold, k8s-golddr, k8s-emerald
+      #   vault.hashicorp.com/auth-path: auth/k8s-{{ .Values.global.cluster }}  
+      #   vault.hashicorp.com/namespace: platform-services
+      #   # licenseplate-nonprod or licenseplate-prod are your options
+      #   vault.hashicorp.com/role: {{ .Values.global.vault.role }} 
+      #   # - The value is the path in Vault where the secret is located.
+      #   vault.hashicorp.com/agent-inject-secret-secrets: {{ .Values.global.licenseplate }}-{{ .Values.global.vault.engine }}/{{ .Values.kilnAPI.vault.secret }}
+      #   # - The template Vault Agent should use for rendering a secret:
+      #   vault.hashicorp.com/agent-inject-template-secrets: |
+      #     {{`{{- with secret `}}"{{ .Values.global.licenseplate }}-{{ .Values.global.vault.engine }}/{{ .Values.kilnAPI.vault.secret }}"{{` }}
+      #     {{- range $k, $v := .Data.data }}
+      #     {{ $k }}={{ $v }}{{ end -}}
+      #     {{- end `}} }}
+      #   # - The value is the path in Vault where the secret is located.
+      #   vault.hashicorp.com/agent-inject-secret-redis-password: {{ .Values.global.licenseplate }}-{{ .Values.global.vault.engine }}/{{ .Values.redis.vault.secret }}
+      #   # - The template Vault Agent should use for rendering a secret:
+      #   vault.hashicorp.com/agent-inject-template-redis-password: |
+      #     {{`{{- with secret `}}"{{ .Values.global.licenseplate }}-{{ .Values.global.vault.engine }}/{{ .Values.redis.vault.secret }}"{{` }}
+      #     {{ .Data.data.password }}
+      #     {{- end `}} }}
       {{- with .Values.kilnAPI.podAnnotations }}
         {{- toYaml . | nindent 8 }}
       {{- end }}
@@ -59,26 +59,26 @@ spec:
         {{- toYaml .Values.kilnAPI.podSecurityContext | nindent 8 }}
       containers:
         - name: {{ .Chart.Name }}
-          command: ["/bin/sh"]
-          args:
-            - -c
-            - |
-              echo "INFO: SSO Client container starting entrypoint..."
-              if [ -s /vault/secrets/redis-password ]; then
-                SECRET_CONTENT=$(cat /vault/secrets/redis-password)
-                export REDIS_PASSWORD=$(echo "${SECRET_CONTENT}" | tr -d '\n\r ')
-                echo "INFO: Redis Password loaded from Vault secret. Length: ${#REDIS_PASSWORD}"
-              else
-                echo "ERROR: /vault/secrets/redis-password is empty or does not exist. Exiting."
-                exit 1
-              fi
+          # command: ["/bin/sh"]
+          # args:
+          #   - -c
+          #   - |
+          #     echo "INFO: SSO Client container starting entrypoint..."
+          #     if [ -s /vault/secrets/redis-password ]; then
+          #       SECRET_CONTENT=$(cat /vault/secrets/redis-password)
+          #       export REDIS_PASSWORD=$(echo "${SECRET_CONTENT}" | tr -d '\n\r ')
+          #       echo "INFO: Redis Password loaded from Vault secret. Length: ${#REDIS_PASSWORD}"
+          #     else
+          #       echo "ERROR: /vault/secrets/redis-password is empty or does not exist. Exiting."
+          #       exit 1
+          #     fi
 
-              if [ -z "${REDIS_PASSWORD}" ]; then
-                echo "ERROR: REDIS_PASSWORD variable is empty after loading from secret. Exiting."
-                exit 1
-              fi
+          #     if [ -z "${REDIS_PASSWORD}" ]; then
+          #       echo "ERROR: REDIS_PASSWORD variable is empty after loading from secret. Exiting."
+          #       exit 1
+          #     fi
 
-              exec npm start
+          #     exec npm start
           securityContext:
             {{- toYaml .Values.kilnAPI.securityContext | nindent 12 }}
           image: {{ .Values.kilnAPI.image.repository }}:{{ .Values.kilnAPI.image.tag }}
